# Data Processing for Introduction into QGIS Desktop

In [79]:
# import libraries

import pandas as pd
import numpy as np
import os
import datetime as dt

pd.set_option('display.max_rows', 50)

In [2]:
# read 2014 data in as data frame

uber2014 = pd.read_csv("~/Downloads/uber_2014_processed.csv")

# downstream conversions would not proceed without including the utc argument, idk???

uber2014["datetime"] = pd.to_datetime(uber2014["datetime"], utc=True)

In [3]:
uber2014.head()

,datetime,lat,lon,base,locationID,borough,zone
0,2014-04-01 00:00:00+00:00,40.7188,-73.9863,B02598,232,Manhattan,Two Bridges/Seward Park
1,2014-04-01 00:00:00+00:00,40.7637,-73.9600,B02598,141,Manhattan,Lenox Hill West
2,2014-04-01 00:00:00+00:00,40.7215,-73.9952,B02682,144,Manhattan,Little Italy/NoLiTa
3,2014-04-01 00:01:00+00:00,40.7355,-73.9966,B02617,113,Manhattan,Greenwich Village North
4,2014-04-01 00:02:00+00:00,40.7184,-73.9601,B02682,255,Brooklyn,Williamsburg (North Side)

In [4]:
# split 2014 data into separate data frames by month

april2014 = uber2014[(uber2014['datetime'].dt.date > pd.to_datetime('2014-03-31').date()) & (uber2014['datetime'].dt.date < pd.to_datetime('2014-05-01').date())]
may2014 = uber2014[(uber2014['datetime'].dt.date > pd.to_datetime('2014-04-30').date()) & (uber2014['datetime'].dt.date < pd.to_datetime('2014-06-01').date())]
june2014 = uber2014[(uber2014['datetime'].dt.date > pd.to_datetime('2014-05-31').date()) & (uber2014['datetime'].dt.date < pd.to_datetime('2014-07-01').date())]
july2014 = uber2014[(uber2014['datetime'].dt.date > pd.to_datetime('2014-06-30').date()) & (uber2014['datetime'].dt.date < pd.to_datetime('2014-08-01').date())]
august2014 = uber2014[(uber2014['datetime'].dt.date > pd.to_datetime('2014-07-31').date()) & (uber2014['datetime'].dt.date < pd.to_datetime('2014-09-01').date())]
september2014 = uber2014[uber2014['datetime'].dt.date > pd.to_datetime('2014-08-31').date()]

In [5]:
# correct errant location_ids

april2014['locationID'][(april2014['locationID'] == 4) & (april2014['zone'] == "Arden Heights")] = 5
may2014['locationID'][(may2014['locationID'] == 4) & (may2014['zone'] == "Arden Heights")] = 5
june2014['locationID'][(june2014['locationID'] == 4) & (june2014['zone'] == "Arden Heights")] = 5
july2014['locationID'][(july2014['locationID'] == 4) & (july2014['zone'] == "Arden Heights")] = 5
august2014['locationID'][(august2014['locationID'] == 4) & (august2014['zone'] == "Arden Heights")] = 5
september2014['locationID'][(september2014['locationID'] == 4) & (september2014['zone'] == "Arden Heights")] = 5

april2014['locationID'][(april2014['locationID'] == 9) & (april2014['zone'] == "Baisley Park")] = 10
may2014['locationID'][(may2014['locationID'] == 9) & (may2014['zone'] == "Baisley Park")] = 10
june2014['locationID'][(june2014['locationID'] == 9) & (june2014['zone'] == "Baisley Park")] = 10
july2014['locationID'][(july2014['locationID'] == 9) & (july2014['zone'] == "Baisley Park")] = 10
august2014['locationID'][(august2014['locationID'] == 9) & (august2014['zone'] == "Baisley Park")] = 10
september2014['locationID'][(september2014['locationID'] == 9) & (september2014['zone'] == "Baisley Park")] = 10

april2014['locationID'][(april2014['locationID'] == 39) & (april2014['zone'] == "Carroll Gardens")] = 40
may2014['locationID'][(may2014['locationID'] == 39) & (may2014['zone'] == "Carroll Gardens")] = 40
june2014['locationID'][(june2014['locationID'] == 39) & (june2014['zone'] == "Carroll Gardens")] = 40
july2014['locationID'][(july2014['locationID'] == 39) & (july2014['zone'] == "Carroll Gardens")] = 40
august2014['locationID'][(august2014['locationID'] == 39) & (august2014['zone'] == "Carroll Gardens")] = 40
september2014['locationID'][(september2014['locationID'] == 39) & (september2014['zone'] == "Carroll Gardens")] = 40

april2014['locationID'][(april2014['locationID'] == 79) & (april2014['zone'] == "East Williamsburg")] = 80
may2014['locationID'][(may2014['locationID'] == 79) & (may2014['zone'] == "East Williamsburg")] = 80
june2014['locationID'][(june2014['locationID'] == 79) & (june2014['zone'] == "East Williamsburg")] = 80
july2014['locationID'][(july2014['locationID'] == 79) & (july2014['zone'] == "East Williamsburg")] = 80
august2014['locationID'][(august2014['locationID'] == 79) & (august2014['zone'] == "East Williamsburg")] = 80
september2014['locationID'][(september2014['locationID'] == 79) & (september2014['zone'] == "East Williamsburg")] = 80

april2014['locationID'][(april2014['locationID'] == 159) & (april2014['zone'] == "Middle Village")] = 160
may2014['locationID'][(may2014['locationID'] == 159) & (may2014['zone'] == "Middle Village")] = 160
june2014['locationID'][(june2014['locationID'] == 159) & (june2014['zone'] == "Middle Village")] = 160
july2014['locationID'][(july2014['locationID'] == 159) & (july2014['zone'] == "Middle Village")] = 160
august2014['locationID'][(august2014['locationID'] == 159) & (august2014['zone'] == "Middle Village")] = 160
september2014['locationID'][(september2014['locationID'] == 159) & (september2014['zone'] == "Middle Village")] = 160

/tmp/ipykernel_752919/1044000987.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  april2014['locationID'][(april2014['locationID'] == 4) & (april2014['zone'] == "Arden Heights")] = 5
/tmp/ipykernel_752919/1044000987.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  april2014['locationID'][(april2014['locationID'] == 4) & (april2014['zone'] == "Arden Heights")] = 5
/tmp/ipykernel_752919/1044000987.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  may2014['locationID'][(may2014['locationID'] == 4) & (may2014['zone'] == "Arden Heights")] = 5
/tmp/ipykernel_752919/1044000987.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  may2014['locationID'][(may2014['locationID'] == 4) & (may2014['zone'] == "Arden Heights")] = 5
/tmp/ipykernel_752919/1044000987.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  june2014['locationID'][(june2014['locationID'] == 4) & (june2014['zone'] == "Arden Heights")] = 5
/tmp/ipykernel_752919/1044000987.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  june2014['locationID'][(june2014['locationID'] == 4) & (june2014['zone'] == "Arden Heights")] = 5
/tmp/ipykernel_752919/1044000987.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  july2014['locationID'][(july2014['locationID'] == 4) & (july2014['zone'] == "Arden Heights")] = 5
/tmp/ipykernel_752919/1044000987.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  july2014['locationID'][(july2014['locationID'] == 4) & (july2014['zone'] == "Arden Heights")] = 5
/tmp/ipykernel_752919/1044000987.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  august2014['locationID'][(august2014['locationID'] == 4) & (august2014['zone'] == "Arden Heights")] = 5
/tmp/ipykernel_752919/1044000987.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  august2014['locationID'][(august2014['locationID'] == 4) & (august2014['zone'] == "Arden Heights")] = 5
/tmp/ipykernel_752919/1044000987.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  september2014['locationID'][(september2014['locationID'] == 4) & (september2014['zone'] == "Arden Heights")] = 5
/tmp/ipykernel_752919/1044000987.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  september2014['locationID'][(september2014['locationID'] == 4) & (september2014['zone'] == "Arden Heights")] = 5
/tmp/ipykernel_752919/1044000987.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  april2014['locationID'][(april2014['locationID'] == 9) & (april2014['zone'] == "Baisley Park")] = 10
/tmp/ipykernel_752919/1044000987.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  april2014['locationID'][(april2014['locationID'] == 9) & (april2014['zone'] == "Baisley Park")] = 10
/tmp/ipykernel_752919/1044000987.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  may2014['locationID'][(may2014['locationID'] == 9) & (may2014['zone'] == "Baisley Park")] = 10
/tmp/ipykernel_752919/1044000987.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  may2014['locationID'][(may2014['locationID'] == 9) & (may2014['zone'] == "Baisley Park")] = 10
/tmp/ipykernel_752919/1044000987.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  june2014['locationID'][(june2014['locationID'] == 9) & (june2014['zone'] == "Baisley Park")] = 10
/tmp/ipykernel_752919/1044000987.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  june2014['locationID'][(june2014['locationID'] == 9) & (june2014['zone'] == "Baisley Park")] = 10
/tmp/ipykernel_752919/1044000987.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  july2014['locationID'][(july2014['locationID'] == 9) & (july2014['zone'] == "Baisley Park")] = 10
/tmp/ipykernel_752919/1044000987.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  july2014['locationID'][(july2014['locationID'] == 9) & (july2014['zone'] == "Baisley Park")] = 10
/tmp/ipykernel_752919/1044000987.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  august2014['locationID'][(august2014['locationID'] == 9) & (august2014['zone'] == "Baisley Park")] = 10
/tmp/ipykernel_752919/1044000987.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  august2014['locationID'][(august2014['locationID'] == 9) & (august2014['zone'] == "Baisley Park")] = 10
/tmp/ipykernel_752919/1044000987.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  september2014['locationID'][(september2014['locationID'] == 9) & (september2014['zone'] == "Baisley Park")] = 10
/tmp/ipykernel_752919/1044000987.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  september2014['locationID'][(september2014['locationID'] == 9) & (september2014['zone'] == "Baisley Park")] = 10
/tmp/ipykernel_752919/1044000987.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  april2014['locationID'][(april2014['locationID'] == 39) & (april2014['zone'] == "Carroll Gardens")] = 40
/tmp/ipykernel_752919/1044000987.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  april2014['locationID'][(april2014['locationID'] == 39) & (april2014['zone'] == "Carroll Gardens")] = 40
/tmp/ipykernel_752919/1044000987.py:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  may2014['locationID'][(may2014['locationID'] == 39) & (may2014['zone'] == "Carroll Gardens")] = 40
/tmp/ipykernel_752919/1044000987.py:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  may2014['locationID'][(may2014['locationID'] == 39) & (may2014['zone'] == "Carroll Gardens")] = 40
/tmp/ipykernel_752919/1044000987.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  june2014['locationID'][(june2014['locationID'] == 39) & (june2014['zone'] == "Carroll Gardens")] = 40
/tmp/ipykernel_752919/1044000987.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  june2014['locationID'][(june2014['locationID'] == 39) & (june2014['zone'] == "Carroll Gardens")] = 40
/tmp/ipykernel_752919/1044000987.py:20: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  july2014['locationID'][(july2014['locationID'] == 39) & (july2014['zone'] == "Carroll Gardens")] = 40
/tmp/ipykernel_752919/1044000987.py:20: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  july2014['locationID'][(july2014['locationID'] == 39) & (july2014['zone'] == "Carroll Gardens")] = 40
/tmp/ipykernel_752919/1044000987.py:21: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  august2014['locationID'][(august2014['locationID'] == 39) & (august2014['zone'] == "Carroll Gardens")] = 40
/tmp/ipykernel_752919/1044000987.py:21: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  august2014['locationID'][(august2014['locationID'] == 39) & (august2014['zone'] == "Carroll Gardens")] = 40
/tmp/ipykernel_752919/1044000987.py:22: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  september2014['locationID'][(september2014['locationID'] == 39) & (september2014['zone'] == "Carroll Gardens")] = 40
/tmp/ipykernel_752919/1044000987.py:22: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  september2014['locationID'][(september2014['locationID'] == 39) & (september2014['zone'] == "Carroll Gardens")] = 40
/tmp/ipykernel_752919/1044000987.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  april2014['locationID'][(april2014['locationID'] == 79) & (april2014['zone'] == "East Williamsburg")] = 80
/tmp/ipykernel_752919/1044000987.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  april2014['locationID'][(april2014['locationID'] == 79) & (april2014['zone'] == "East Williamsburg")] = 80
/tmp/ipykernel_752919/1044000987.py:25: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  may2014['locationID'][(may2014['locationID'] == 79) & (may2014['zone'] == "East Williamsburg")] = 80
/tmp/ipykernel_752919/1044000987.py:25: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  may2014['locationID'][(may2014['locationID'] == 79) & (may2014['zone'] == "East Williamsburg")] = 80
/tmp/ipykernel_752919/1044000987.py:26: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  june2014['locationID'][(june2014['locationID'] == 79) & (june2014['zone'] == "East Williamsburg")] = 80
/tmp/ipykernel_752919/1044000987.py:26: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  june2014['locationID'][(june2014['locationID'] == 79) & (june2014['zone'] == "East Williamsburg")] = 80
/tmp/ipykernel_752919/1044000987.py:27: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  july2014['locationID'][(july2014['locationID'] == 79) & (july2014['zone'] == "East Williamsburg")] = 80
/tmp/ipykernel_752919/1044000987.py:27: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  july2014['locationID'][(july2014['locationID'] == 79) & (july2014['zone'] == "East Williamsburg")] = 80
/tmp/ipykernel_752919/1044000987.py:28: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  august2014['locationID'][(august2014['locationID'] == 79) & (august2014['zone'] == "East Williamsburg")] = 80
/tmp/ipykernel_752919/1044000987.py:28: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  august2014['locationID'][(august2014['locationID'] == 79) & (august2014['zone'] == "East Williamsburg")] = 80
/tmp/ipykernel_752919/1044000987.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  september2014['locationID'][(september2014['locationID'] == 79) & (september2014['zone'] == "East Williamsburg")] = 80
/tmp/ipykernel_752919/1044000987.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  september2014['locationID'][(september2014['locationID'] == 79) & (september2014['zone'] == "East Williamsburg")] = 80
/tmp/ipykernel_752919/1044000987.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  april2014['locationID'][(april2014['locationID'] == 159) & (april2014['zone'] == "Middle Village")] = 160
/tmp/ipykernel_752919/1044000987.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  april2014['locationID'][(april2014['locationID'] == 159) & (april2014['zone'] == "Middle Village")] = 160
/tmp/ipykernel_752919/1044000987.py:32: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  may2014['locationID'][(may2014['locationID'] == 159) & (may2014['zone'] == "Middle Village")] = 160
/tmp/ipykernel_752919/1044000987.py:32: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  may2014['locationID'][(may2014['locationID'] == 159) & (may2014['zone'] == "Middle Village")] = 160
/tmp/ipykernel_752919/1044000987.py:33: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  june2014['locationID'][(june2014['locationID'] == 159) & (june2014['zone'] == "Middle Village")] = 160
/tmp/ipykernel_752919/1044000987.py:33: SettingWithCopyWarning:

In [6]:
# read 2015 data csv file into a dataframe

csv_file = "~/IDC5131_Dist_Comp/Project_2_files/exported_csvs/2015/uber_janjune15_wcodes_centroids.csv"
uber2015 = pd.read_csv(csv_file)
uber2015.head()

,Unnamed: 0,Dispatching_base_num,Pickup_date,Affiliated_base_num,locationID,borough,zone,xCentroid,yCentroid
0,1,B02617,2015/05/17 09:47:00,B02617,141,Manhattan,Lenox Hill West,-73.9596,40.7669
1,2,B02617,2015/05/17 09:47:00,B02617,65,Brooklyn,Downtown Brooklyn/MetroTech,-73.9861,40.6953
2,3,B02617,2015/05/17 09:47:00,B02617,100,Manhattan,Garment District,-73.9888,40.7535
3,4,B02617,2015/05/17 09:47:00,B02774,80,Brooklyn,East Williamsburg,-73.9368,40.7154
4,5,B02617,2015/05/17 09:47:00,B02617,90,Manhattan,Flatiron,-73.9970,40.7423

In [7]:
# create column headings
col_order = ['datetime', 'lat', 'lon', 'base', 'locationID', 'borough', 'zone']

In [8]:
# reformat 2015 data
# Convert date to datetime format
uber2015['datetime'] = pd.to_datetime(uber2015['Pickup_date'])

# Drop extraneous columns
uber2015 = uber2015.drop(['Unnamed: 0', 'Dispatching_base_num', 'Pickup_date'], axis = 1)

# Rename columns to obtain the same format
uber2015 = uber2015.rename(columns = {"Affiliated_base_num": "base", "xCentroid": "lon", "yCentroid":"lat"})

# Reorder the columns
uber2015 = uber2015[col_order]

# Sort by datetime
uber2015 = uber2015.sort_values("datetime").reset_index(drop = True)

# Final format
uber2015.head()

,datetime,lat,lon,base,locationID,borough,zone
0,2015-01-01 00:00:05,40.7188,-73.9574,B02764,255,Brooklyn,Williamsburg (North Side)
1,2015-01-01 00:00:05,40.7209,-73.9969,B02598,144,Manhattan,Little Italy/NoLiTa
2,2015-01-01 00:00:08,40.7326,-73.9943,B02682,113,Manhattan,Greenwich Village North
3,2015-01-01 00:00:11,40.7403,-73.9905,B02617,234,Manhattan,Union Sq
4,2015-01-01 00:00:13,40.7147,-73.9830,B02764,232,Manhattan,Two Bridges/Seward Park

In [9]:
# split 2015 data into separate data frames by month

jan2015 = uber2015[uber2015['datetime'].dt.date < pd.to_datetime('2015-02-01').date()]
feb2015 = uber2015[(uber2015['datetime'].dt.date > pd.to_datetime('2015-01-31').date()) & (uber2015['datetime'].dt.date < pd.to_datetime('2015-03-01').date())]
march2015 = uber2015[(uber2015['datetime'].dt.date > pd.to_datetime('2015-02-28').date()) & (uber2015['datetime'].dt.date < pd.to_datetime('2015-04-01').date())]
april2015 = uber2015[(uber2015['datetime'].dt.date > pd.to_datetime('2015-03-31').date()) & (uber2015['datetime'].dt.date < pd.to_datetime('2015-05-01').date())]
may2015 = uber2015[(uber2015['datetime'].dt.date > pd.to_datetime('2015-04-30').date()) & (uber2015['datetime'].dt.date < pd.to_datetime('2015-06-01').date())]
june2015 = uber2015[uber2015['datetime'].dt.date > pd.to_datetime('2015-05-31').date()]

In [10]:
# load all dataframes into list that can be iterated over

df_list = [april2014, may2014, june2014, july2014, august2014, september2014, jan2015, feb2015, march2015, april2015, may2015, june2015]

In [11]:
# for every dataframe in list, add a counter column of ones, then group by locationID, borough, and zone, and sum the counts

new_data = []
for i in df_list:
    i['count'] = 1
    j = i.groupby(['locationID', 'borough', 'zone']).sum('count').reset_index()
    new_data.append(j)

/tmp/ipykernel_752919/106587110.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  i['count'] = 1
/tmp/ipykernel_752919/106587110.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  i['count'] = 1
/tmp/ipykernel_752919/106587110.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  i['count'] = 1
/tmp/ipykernel_752919/106587110.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  i['count'] = 1
/tmp/ipykernel_752919/106587110.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  i['count'] = 1
/tmp/ipykernel_752919/106587110.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  i['count'] = 1
/tmp/ipykernel_752919/106587110.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  i['count'] = 1
/tmp/ipykernel_752919/106587110.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  i['count'] = 1
/tmp/ipykernel_752919/106587110.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  i['count'] = 1
/tmp/ipykernel_752919/106587110.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  i['count'] = 1
/tmp/ipykernel_752919/106587110.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  i['count'] = 1
/tmp/ipykernel_752919/106587110.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  i['count'] = 1

In [12]:
# create a list of corrective coefficients to account for monthly growth in uber patronage over the period of analysis  
# this will allow us to make apples to apples comparisons for departures between months

sum_counts = []
for i in new_data:
    sum_counts.append(i['count'].sum())
    
coefficients = np.mean(sum_counts)/sum_counts
coefficients

array([2.81266659, 2.43215946, 2.39366604, 1.99877415, 1.92650158,
       1.55006724, 0.79821619, 0.68893056, 0.69007704, 0.68367059,
       0.57851588, 0.55360637])

In [13]:
# add empty column, corrected count, to each dataframe in list

for i in new_data:
    i["corrected_count"] = None

In [14]:
# fill empty column with corrected counts (count * corrective coefficient for each month)

for i,j in zip(new_data, coefficients):
    i['corrected_count'] = i['count'] * j

In [15]:
# load taxi zones as data frames and subset those zones with index locationID < 264

taxi_zones = pd.read_csv("/home/richard/Downloads/taxi+_zone_lookup.csv")
taxi_zones = taxi_zones.rename(columns = {"LocationID": "locationID"})
taxi_zones = taxi_zones[taxi_zones.locationID < 264]

In [16]:
# find missing locationIDs in all data frames, insert those location IDs and fill in other elements in row with 0
# add all ride counts from the dfs into a list

all_counts = []
for count,df in enumerate(new_data):
    diff = pd.DataFrame(taxi_zones.locationID[~taxi_zones.locationID.isin(df.locationID)])
    join_diff = pd.concat([df,diff], axis = 0, ignore_index=True)
    new_data[count] = pd.concat([new_data[count],diff], axis = 0, ignore_index=True)
    join_diff = join_diff.fillna(0)
    new_data[count] = new_data[count].fillna(0)
    join_diff = join_diff.sort_values(by='locationID', ignore_index = True)
    new_data[count] = join_diff.sort_values(by='locationID', ignore_index = True)
    all_counts.append(join_diff['count'])

In [17]:
# calculate average ridership per location_ID and insert into list

avg_counts = np.mean(all_counts, axis = 0).astype(float)

In [18]:
# add empty column, rider shifts (denoting shifts from average), to each dataframe in list

for df in new_data:
    df["rider_shift"] = None

In [22]:
# fill empty column with corrected counts (count * corrective coefficient for each month)

for df in new_data:
    df['rider_shift'] = df['corrected_count'] - avg_counts

In [35]:
# create list of csv titles
df_list_strs = ['april2014', 'may2014', 'june2014', 'july2014', 'august2014', 'september2014', 'jan2015', 'feb2015', 'march2015', 'april2015', 'may2015', 'june2015']

['april2014',
 'may2014',
 'june2014',
 'july2014',
 'august2014',
 'september2014',
 'jan2015',
 'feb2015',
 'march2015',
 'april2015',
 'may2015',
 'june2015']

In [ ]:
# export every df in new_data list as csv file

for count, df in enumerate(new_data):
    df.to_csv("~/IDC5131_Dist_Comp/Project_2_files/csvs_w_vars/" + df_list_strs[count] + ".csv")